version: '2'
services:
  spark-master:
    build: ./master
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
  spark-worker-1:
    build: ./worker
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
  zeppelin:
    build: ./zeppelin
    container_name: zeppelin
    ports:
      - 80:8080
    volumes:
      - ./notebook:/opt/zeppelin/notebook
    environment:
      SPARK_MASTER: "spark://spark-master:7077"
      MASTER: "spark://spark-master:7077"
    depends_on:
      - spark-master
      - spark-worker-1